//
//  Q2ViewController.swift
//  ProjEuluer
//
//  Created by Julien Bankier on 5/5/17.
//  Copyright © 2017 Julien Bankier. All rights reserved.
//

import UIKit

class Q2ViewController: PEViewController {
    var projEuleurSolution2 = 0
    
    override func viewDidLoad() {
        super.viewDidLoad()
        question.text = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n\n\n 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... \n\n\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. "

        question.font = UIFont.systemFont(ofSize: 15)
        response.text = String(self.createFibSequenceFrom(a: 0, b: 1, celing: 4000000))
        self.adjustTextSizeForLabel(label: question)
        self.adjustTextSizeForLabel(label: response)
    }
    
    func createFibSequenceFrom(a: Int, b: Int, celing: Int) -> Int{
        let fibNum = a + b
        let newA = b
        let newB = fibNum
        if fibNum % 2 == 0 {
            projEuleurSolution2 = projEuleurSolution2 + fibNum
        }
        if newA <= celing || newB <= celing {
            _ = createFibSequenceFrom(a: newA, b: newB, celing: celing)
        }
        return projEuleurSolution2
    }

}
